name: Rust
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/dependabot.yml"
    branches: [develop]

env:
  # From-scratch builds with incremental compilation enabled adds unneeded performance and disk overhead. 
  CARGO_INCREMENTAL: "0"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        make_target: ["check-licenses", "build", "integ"]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - os: windows-latest
            make_target: check-licenses
          - os: macos-latest
            make_target: check-licenses
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            .cargo
          # you can edit the .github/cache_bust file if you need to clear the cache
          key: ${{ hashFiles('.github/cache_bust') }}-${{ runner.os }}-${{ matrix.make_target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ hashFiles('.github/cache_bust') }}-${{ runner.os }}-${{ matrix.make_target }}
      - run: rustup default 1.71.1
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: make ${{ matrix.make_target }}
